FROM eclipse-temurin:17-alpine
EXPOSE 8080
COPY ./build/libs/dental-clinic-service-0.0.1.jar /usr/app/
WORKDIR /usr/app

ENTRYPOINT ["java", "-Dserver.port=${SERVICE_PORT}", "-Dspring.profiles.active=${ACTIVE_PROILE}", "-jar", "dental-clinic-service-0.0.1.jar"]