FROM eclipse-temurin:17-jre-alpine
EXPOSE 8080
RUN addgroup --system javauser && adduser -S -s /bin/false -G javauser javauser
COPY ./build/libs/*.jar /usr/app/main.jar
WORKDIR /usr/app
RUN chown -R javauser:javauser /usr/app
USER javauser
ENTRYPOINT ["java", "-Dserver.port=${SERVICE_PORT}", "-Dspring.profiles.active=${ACTIVE_PROILE}", "-jar", "main.jar"]