# ===============================
# Dental Clinic Service Properties
# ===============================
server:
  port: 9090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dental-clinic
    username: clinic
    password: clinic
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false

# ===============================
# Management Endpoint Properties
# ===============================
management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env,beans"

# ===============================
# Health endpoints properties
# ===============================
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
      group:
        liveness:
          include: livenessState, ping
          show-details: always
        readiness:
          include: readinessState, ping
          show-details: always
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true
