# ===============================
# Dental Clinic Service Properties
# ===============================
server:
  port: 9090
  shutdown: graceful

spring:
  datasource:
    url: jdbc:postgresql://dpg-ccrin1pa6gdl22bl506g-a.oregon-postgres.render.com:5432/dental_clinic
    username: root
    password: Leue0BR6H7QopFSkPNFPl3mnOWQM0yb7
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
    properties:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
  jackson:
    default-property-inclusion:
    - non_null
    - non_empty
  config:
    activate:
      on-profile:
      on-cloud-platform:

# ===============================
# Management Endpoint Properties
# ===============================
management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env,beans"

# ===============================
# Health endpoints properties
# ===============================
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
      group:
        liveness:
          include: livenessState, ping
          show-details: always
        readiness:
          include: readinessState, ping
          show-details: always
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true

---

spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:postgresql://dpg-ccrin1pa6gdl22bl506g-a:5432/dental_clinic
