version: '3.9'

services:
      
  
  dc-postgres:
    container_name: dc-postgres
    restart: always
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
    - POSTGRES_PASSWORD=toor
    - POSTGRES_DB=dental_clinic
    - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - 'postgres-data:/var/lib/postgresql/data/pgdata'

  
  dc-dental-clinic-service:
    container_name: dc-dental-clinic-service
    image: dental-clinic-service:latest
    ports:
    - 8082:8080
    environment:
      - SERVICE_PORT=8080
      - ACTIVE_PROILE=docker
    depends_on:      
      - dc-postgres
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3      


volumes:
  postgres-data:
    external: true
